- name: Installer Grafana en contournant les erreurs Zabbix
  hosts: monitoring
  become: true

  tasks:
    - name: Corriger les paquets cassés
      shell: |
        dpkg --configure -a || true
        apt --fix-broken install -y || true

    - name: Ajouter les dépendances nécessaires
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - gnupg2
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG de Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Ajouter le dépôt Grafana
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present
        filename: grafana

    - name: Mise à jour après dépôt Grafana
      apt:
        update_cache: yes

    - name: Installer Grafana avec apt
      shell: |
        DEBIAN_FRONTEND=noninteractive apt install grafana -y || true

    - name: Activer et démarrer le service Grafana
      systemd:
        name: grafana-server
        enabled: true
        state: started
